version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - recipe-net

  app:
    image: khaled963/recipecliapp:latest
    build:
      context: .
      args:
        CONNECTION_STRING_FILE: /run/secrets/connection_string
    environment:
      ConnectionStrings__DefaultConnection_FILE: /run/secrets/connection_string
    secrets:
      - connection_string
    depends_on:
      - db
    networks:
      - recipe-net

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  connection_string:
    file: ./secrets/connection_string.txt

networks:
  recipe-net:

volumes:
  db-data:
