version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - recipe-net

  app:
    build:
      context: .
      args:
        CONNECTION_STRING: "${CONNECTION_STRING_DOCKER}"
    environment:
      ConnectionStrings__DefaultConnection: "${CONNECTION_STRING_DOCKER}"
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - db
    networks:
      - recipe-net

networks:
  recipe-net:

volumes:
  db-data:
